title: Seunghoon Lee
tagline: Business, Economics, and Applied Statistics
description: >-
  A blog focused on advanced statistics and econometric modeling
url: "https://samiswkd.github.io"

author:
  name: Your Name
  email: your.email@example.com

# Remote theme
remote_theme: cotes2020/jekyll-theme-chirpy

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page:num/"

# SEO
timezone: Asia/Seoul
lang: en
